name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      APP_SUPABASE_URL: ${{ secrets.APP_SUPABASE_URL }}
      APP_SUPABASE_KEY: ${{ secrets.APP_SUPABASE_KEY }}

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-on-failure: "false"

      - uses: cargo-bins/cargo-binstall@main

      - name: Install dioxus-cli
        run: cargo binstall -y dioxus-cli@0.6.1 --force

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Build
        run: dx build --release --platform web

      - name: Copy index to 404.html for gh-pages
        run: cp target/dx/language-forum/release/web/public/index.html target/dx/language-forum/release/web/public/404.html

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/dx/language-forum/release/web/public
